services:
    OHMedia\EmailBundle\Command\CleanupCommand:
        arguments: ["@doctrine.orm.entity_manager", "%ohmedia_email.cleanup%"]
        tags: ["console.command"]

    OHMedia\EmailBundle\Command\SendCommand:
        arguments: ["@doctrine.orm.entity_manager", "@ohmedia_email.sender"]
        tags: ["console.command"]

    OHMedia\EmailBundle\Repository\EmailRepository:
        arguments: ["@Doctrine\\Persistence\\ManagerRegistry"]
        tags: ["doctrine.repository_service"]

    OHMedia\EmailBundle\EventListener\EmailPrePersist:
        arguments: ["@doctrine.orm.entity_manager", "@twig"]
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'prePersist'
                entity: 'OHMedia\EmailBundle\Entity\Email'
