services:
    OHMedia\EmailBundle\Cleanup\EmailCleaner:
        arguments: ["@oh_media_email.repository", "%oh_media_email.cleanup%"]
        tags: ["oh_media_cleanup.cleaner"]

    OHMedia\EmailBundle\Repository\EmailRepository:
        arguments: ["@Doctrine\\Persistence\\ManagerRegistry"]
        tags: ["doctrine.repository_service"]

    oh_media_email.repository:
        alias: OHMedia\EmailBundle\Repository\EmailRepository

    OHMedia\EmailBundle\EventListener\EmailSubscriber:
        arguments: ["@doctrine.orm.entity_manager", "@mailer", "@twig", "%oh_media_email.from_email%", "%oh_media_email.from_name%", "%oh_media_email.subject_prefix%"]
        tags: ["doctrine.event_subscriber"]
