services:
    OHMedia\EmailBundle\Service\EmailHelper:
        arguments: ["@doctrine.orm.entity_manager", "@ohmedia_settings.settings", "@twig", "%ohmedia_email.stylesheet%"]

    OHMedia\EmailBundle\Command\CleanupCommand:
        arguments: ["@doctrine.orm.entity_manager", "%ohmedia_email.cleanup%"]
        tags: ["console.command"]

    OHMedia\EmailBundle\Command\SendCommand:
        arguments: ["@doctrine.orm.entity_manager", "@ohmedia_email.sender"]
        tags: ["console.command"]

    OHMedia\EmailBundle\Repository\EmailRepository:
        arguments: ["@Doctrine\\Persistence\\ManagerRegistry"]
        tags: ["doctrine.repository_service"]
